2024-03-14 18:27:10,351 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-14 18:27:10,352 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Configure stats pid to 4180330
2024-03-14 18:27:10,352 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Loading settings from /home/aabdalq/.config/wandb/settings
2024-03-14 18:27:10,352 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Loading settings from /home/aabdalq/projects/deeplearning/jbNDT/jbndt/wandb/settings
2024-03-14 18:27:10,352 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-14 18:27:10,352 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-14 18:27:10,353 WARNING MainThread:4180330 [wandb_setup.py:_flush():76] Could not find program at main.py
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'main.py'}
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:_log_setup():526] Logging user logs to /home/aabdalq/projects/deeplearning/jbNDT/jbndt/wandb/run-20240314_182710-x3t6kjnp/logs/debug.log
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:_log_setup():527] Logging internal logs to /home/aabdalq/projects/deeplearning/jbNDT/jbndt/wandb/run-20240314_182710-x3t6kjnp/logs/debug-internal.log
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:init():566] calling init triggers
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {'input_dim': 182, 'sequence_length': 140, 'behavioral_dim': 2, 'factor_dim': 64, 'head_dim': 32, 'num_heads': 2, 'num_layers': 4, 'mha_dropout': 0.5, 'forward_context': 15, 'backward_context': 35, 'ffn_dim': 128, 'ffn_dropout': 0.2, 'post_readin_dropout': 0.2, 'post_encoder_dropout': 0.2, 'post_positional_embedding_dropout': 0.5, 'epochs': 1500, 'batch_size': 32, 'lr_init': 0.001, 'weight_decay': 5e-06, 'loss_balance_factor': 50000}
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:init():616] starting backend
2024-03-14 18:27:10,353 INFO    MainThread:4180330 [wandb_init.py:init():620] setting up manager
2024-03-14 18:27:10,354 INFO    MainThread:4180330 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-14 18:27:10,357 INFO    MainThread:4180330 [wandb_init.py:init():628] backend started and connected
2024-03-14 18:27:10,362 INFO    MainThread:4180330 [wandb_init.py:init():720] updated telemetry
2024-03-14 18:27:10,448 INFO    MainThread:4180330 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-14 18:27:10,921 INFO    MainThread:4180330 [wandb_run.py:_on_init():2262] communicating current version
2024-03-14 18:27:10,990 INFO    MainThread:4180330 [wandb_run.py:_on_init():2271] got version response 
2024-03-14 18:27:10,990 INFO    MainThread:4180330 [wandb_init.py:init():804] starting run threads in backend
2024-03-14 18:27:11,731 WARNING MainThread:4180330 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/aabdalq/miniconda3/envs/nlb/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-14 18:27:18,690 WARNING MsgRouterThr:4180330 [router.py:message_loop():77] message_loop has been closed
